;Criando variaveis em Common lisp e entradas inputs
(defun Triangulo ()
  (format t "Um triângulo pitagórico tem o lado C^2 = A^2 + B^2~%")
  (format t "Coloque o comprimento do lado A de um triângulo: ~%")
  (let ((Comprimento_Triangulo_A (read))
        (Comprimento_Triangulo_B (progn (format t "Coloque o comprimento do lado B de um triângulo: ~%") (read)))
        (Comprimento_Triangulo_C (progn (format t "Coloque o comprimento do lado C de um triângulo: ~%") (read))))
    (if (= (* Comprimento_Triangulo_C Comprimento_Triangulo_C) (+ (* Comprimento_Triangulo_A Comprimento_Triangulo_A) (* Comprimento_Triangulo_B Comprimento_Triangulo_B)))
        (format t "É pitagórico!~%")
        (format t "Não é pitagórico!~%"))))
